### PR TITLE
LPS-79496 Additional checks

### PR DESCRIPTION
**Pull request by christopherbryanboyd**
Hey @gamerson , these are the updates requested here https://github.com/Ithildir/liferay-portal/pull/979

### CODE REVIEW

**Comment by christopherbryanboyd** [comment]
ci:test:relevant

**Comment by gamerson** [comment]
sent https://github.com/Ithildir/liferay-portal/pull/986

**Comment by gamerson** [comment]
missing commits sent here: https://github.com/gamerson/liferay-portal/pull/120

**Comment by christopherbryanboyd** [comment]
Thank you @gamerson !

**Pull request closed without merging**
