### PR TITLE
LPS-75556 Remove definitions.vm file, not used any more

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:retest

**Comment by izaera** [comment]
@gamerson some of the tests are failing and are true positives. I'm trying to fix them now.
Will push when it is ready.

**Comment by gamerson** [comment]
ci:stop

**Comment by gamerson** [comment]
ok thanks

**Comment by izaera** [comment]
ci:retest

**Comment by izaera** [comment]
@gamerson This seems to be ready 👍

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/Ithildir/liferay-portal/pull/830. [See changes here.](https://github.com/gamerson/liferay-portal/compare/3b54cc9~4...3b54cc9) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/Ithildir/liferay-portal/pull/831. [See changes here.](https://github.com/gamerson/liferay-portal/compare/8c371a5~5...8c371a5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
