### PR TITLE
LPS-94878 (Thin Spring) LPS-95285 (Support PortletMVC4Spring)

### PR DESCRIPTION
**Pull request by ngriffin7a**
LPS-94878 Support PortletMVC4Spring in the Spring MVC project template
LPS-95285 As a developer I would like spring mvc portlets to reuse the spring stack provided by Liferay portal

### CODE REVIEW

**Comment by ngriffin7a** [comment]
@gamerson This PR builds upon commits by you and @rotty3000.

I did what you asked -- Rather than having multiple templates, I made an **uber** project-templates-spring-mvc-portlet that supports the following permutations using Velocity conditionals:

framework | frameworkDependencies | viewType | liferayVersion
--------- | --------------------- | -------- | --------------
springportletmvc | embedded (thick) | jsp | 7.0
springportletmvc | embedded (thick) | thymeleaf | 7.0
springportletmvc | embedded (thick) | jsp | 7.1
springportletmvc | embedded (thick) | thymeleaf | 7.1
springportletmvc | provided (thin) | jsp | 7.1
springportletmvc | provided (thin) | thymeleaf | 7.1
springportletmvc | embedded (thick) | jsp | 7.2
springportletmvc | embedded (thick) | thymeleaf | 7.2
springportletmvc | provided (thin) | jsp | 7.2
springportletmvc | provided (thin) | thymeleaf | 7.2
springportletmvc | embedded (thick) | jsp | 7.3
springportletmvc | embedded (thick) | thymeleaf | 7.3
portletmvc4spring | embedded (thick) | jsp | 7.1
portletmvc4spring | embedded (thick) | thymeleaf | 7.1
portletmvc4spring | embedded (thick) | jsp | 7.2
portletmvc4spring | embedded (thick) | thymeleaf | 7.2
portletmvc4spring | embedded (thick) | jsp | 7.3
portletmvc4spring | embedded (thick) | thymeleaf | 7.3
portletmvc4spring | embedded (thin) | jsp | 7.3
portletmvc4spring | embedded (thin) | thymeleaf | 7.3

Note that the "thin" configurations won't work just yet because Ray is still working on getting thin working in the core. Regardless, they're all setup for thin once Ray's work is done.

Also, it's won't be possible to test the 7.3 permutations until the 7.3 DTDs are available.

Finally, if there are failures in the ProjectTemplateFilesTest.java I'd appreciate it if you would fix them for me.

/cc @david-truong

**Comment by gamerson** [comment]
Hey @ngriffin7a  

Thanks for the update.  I'll work on this this week.

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Review stage one has passed and now moved over to Lawrence for another round: https://github.com/lawrence-lee/liferay-portal/pull/120

Thanks again Neil!

**Pull request closed without merging**
