### PR TITLE
LPS-100078 Project Templates 5.0

### PR DESCRIPTION
**Pull request by christopherbryanboyd**

### CODE REVIEW

**Comment by christopherbryanboyd** [comment]
ci:test:relevant

**Comment by christopherbryanboyd** [comment]
ci:test:sf

**Comment by christopherbryanboyd** [comment]
ci:test:project-templates

**Comment by christopherbryanboyd** [comment]
ci:test:relevant

**Comment by christopherbryanboyd** [comment]
ci:test:sf

**Comment by christopherbryanboyd** [comment]
ci:test:project-templates

**Comment by christopherbryanboyd** [comment]
ci:test:relevant

**Comment by christopherbryanboyd** [comment]
ci:test:project-templates

**Comment by christopherbryanboyd** [comment]
ci:test:project-templates

**Comment by christopherbryanboyd** [comment]
ci:test:relevant

**Comment by christopherbryanboyd** [comment]
ci:test:sf

**Comment by christopherbryanboyd** [comment]
ci:test:relevant

**Comment by christopherbryanboyd** [comment]
ci:test:project-templates

**Comment by christopherbryanboyd** [comment]
ci:test:sf

**Comment by christopherbryanboyd** [comment]
ci:test:sf

**Comment by christopherbryanboyd** [comment]
ci:test:relevant

**Comment by christopherbryanboyd** [comment]
ci:test:project-templates

**Comment by christopherbryanboyd** [comment]
ci:test:cancel

**Comment by christopherbryanboyd** [comment]
ci:test:relevant

**Comment by christopherbryanboyd** [comment]
ci:test:sf

**Comment by christopherbryanboyd** [comment]
ci:test:project-templates

**Comment by christopherbryanboyd** [comment]
ci:test:relevant

**Comment by christopherbryanboyd** [comment]
ci:test:project-templates

**Comment by christopherbryanboyd** [comment]
ci:test:sf

**Comment by christopherbryanboyd** [comment]
@gamerson Looks like this one is ready for review :+1:

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/petershin/liferay-portal/pull/746. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
