### PR TITLE
LPS-86838 Allowed create modules-ext project from maven archetype

### PR DESCRIPTION
**Pull request by Camork**

### CODE REVIEW

**Comment by gamerson** [comment]
hey @Camork  can you add a test case to ProjectTemplatesTest?  thanks!

**Comment by Camork** [comment]
OK

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/Camork/liferay-portal/pull/1. [See changes here.](https://github.com/gamerson/liferay-portal/compare/1c55cba3cc50~3...1c55cba3cc50) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
