### PR TITLE
LPS 186072 spring boot

### PR DESCRIPTION
**Pull request by gamerson**
- LPS-186072 Allow configuration of public endpoints
- LPS-186072 FAKE GRADLE CACHE

### CODE REVIEW

**Comment by gamerson** [comment]
ci:forward

**Comment by gamerson** [comment]
ci:test:liferay-sample-workspace

**Comment by gamerson** [comment]
ci:forward

**Comment by gamerson** [comment]
ci:test:stable

**Comment by michaelhashimoto** [comment]
ci:test:stable

**Comment by gamerson** [comment]
ci:forward

**Pull request closed without merging**
