### PR TITLE
LPS-118918 FAKE GRADLE CACHE

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:gradle-plugins

**Comment by lawrence-lee** [comment]
ci:test:gradle-plugins

**Comment by lawrence-lee** [comment]
ci:test:gradle-plugins

**Comment by lawrence-lee** [comment]
I'm not sure how to get the tests to run in CI, but I was able to run the `gradleTest` locally and verify it failed before the fix and passes after the fix.

**Comment by lawrence-lee** [comment]
ci:test:gradle-plugins

**Comment by lawrence-lee** [comment]
ci:test:gradle-plugins

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/petershin/liferay-portal/pull/1152. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-portal/pull/464. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
