### PR TITLE
Remove snapshot dependencies

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
cI:test:sf

**Comment by lawrence-lee** [comment]
ci:test:relevant

**Comment by lawrence-lee** [comment]
ci:reopen

**Comment by lawrence-lee** [comment]
ci:test:relevant

**Comment by lawrence-lee** [comment]
@gamerson The failures look unrelated to ProjectTemplatesTest

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/Ithildir/liferay-portal/pull/1041. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
