### PR TITLE
LPS-86544 fix the issue of wrong dtd version when choose a version of liferay

### PR DESCRIPTION
**Pull request by Seiphon**
Hi @gamerson 

This time I added the fake grade cache.

Br,
Seiphon

### CODE REVIEW

**Comment by Seiphon** [comment]
ci:test:project-templates

**Comment by Seiphon** [comment]
ci:test:project-templates

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/petershin/liferay-portal/pull/273. [See changes here.](https://github.com/gamerson/liferay-portal/compare/ec6a325e5bb3~1...ec6a325e5bb3) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-portal/pull/230. [See changes here.](https://github.com/gamerson/liferay-portal/compare/81102fce588e~3...81102fce588e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
