### PR TITLE
LPD-24900

### PR DESCRIPTION
**Pull request by gamerson**
- **LPD-24900 ensure that CET Impl classes will use company scoping**
- **LPD-24900 pass companyId to FeatureFlagManagerUtil.isEnabled**

### CODE REVIEW

**Review by rotty3000 — APPROVED** [review]
LGTM

**Comment by gamerson** [comment]
ci:forward

**Review by drewbrokke — APPROVED** [review]
LGTM 👍

**Comment by gamerson** [comment]
Hey @drewbrokke  any idea how to check why these failed? 

[playwright-js-tomcat90-mysql57-jdk8/0/0](https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/870965//consoleText) - [Playwright Report](https://testray.liferay.com/reports/production/logs/2024-05/test-1-36/test-portal-acceptance-pullrequest(master)/5999/playwright-js-tomcat90-mysql57-jdk8/0/0/playwright-report/index.html)
[client-extension-web/themeSpritemap.spec.ts](https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/870965/testReport/client-extension-web_themeSpritemap.spec/ts)
[client-extension-web/globalJS.spec.ts](https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/870965/testReport/client-extension-web_globalJS.spec/ts)
[client-extension-web/iframe.spec.ts](https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/870965/testReport/client-extension-web_iframe.spec/ts)
...

I've never checked the playwright tests before.

**Comment by drewbrokke** [comment]
@gamerson the [Playwright Report](https://testray.liferay.com/reports/production/logs/2024-05/test-1-36/test-portal-acceptance-pullrequest(master)/5999/playwright-js-tomcat90-mysql57-jdk8/0/0/playwright-report/index.html) is pretty detailed. So far it looks like a few different kinds of failures. I see a few where the hashed file differs. I'll take a further look after the standup today.

**Pull request closed without merging**
