### PR TITLE
LPS-69230 Only deploy current application in the new context

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by csierra** [comment]
hey @gamerson @ithildir

these are the changes we discussed... I have not tested them since I don't know how 😢 

how are these templates used? are you thinking about creating another one for jax-ws?

**Comment by gamerson** [comment]
@csierra  so Andrea proposed to rename jax-rs template to just 'rest' so this would be the only 'rest' service template and it would use jax-rs.  So I don't think there is a proposal to add another template inaddition to this one.

**Comment by gamerson** [comment]
i'll rebase your changes on top of https://github.com/brianchandotcom/liferay-portal/pull/44762

**Comment by gamerson** [comment]
@csierra sent your changes along with test here: https://github.com/Ithildir/liferay-portal/pull/550  thanks for the review.

**Pull request closed without merging**
