### PR TITLE
LPS-121466 FAKE GRADLE CACHE

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:relevant

**Comment by lawrence-lee** [comment]
ci:test:sf

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
@gamerson, the latest service builder generates code that requires the next major version of portal.kernel code, so these tests will fail. 

If you think that's okay, these tests will pass `ci:test:relevant` and `ci:test:stable`. If its not okay. then we cant have this PR until we have 7.3 GA6 product key live.

**Comment by gamerson** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
ci:test:relevant

**Comment by lawrence-lee** [comment]
ci:test:sf

**Comment by lawrence-lee** [comment]
ci:test:sf

**Comment by lawrence-lee** [comment]
sent here after updating product info https://github.com/gamerson/liferay-portal/pull/471

**Pull request closed without merging**
