### PR TITLE
LPS-75889 Modify blade's Angular template to make it truly instanceable

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
Fixing it. Will push in a moment.

**Comment by izaera** [comment]
ci:retest

**Comment by gamerson** [comment]
hey @izaera  can you check this ? 

https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=4,label_exp=!master/173380//testReport/com.liferay.project.templates/ProjectTemplatesTest/testBuildTemplateNpmAngularPortlet

**Comment by izaera** [comment]
Will resend in another pull

**Pull request closed without merging**
