### PR TITLE
LCD 14229 client extension templates SF fix

### PR DESCRIPTION
**Pull request by gamerson**
- LPS-155410 Interfaces have been renamed
- LCD-14229 Don't add cet in client-extension-types.json if there is no name in annotation CETType
- LCD-14229 Catch more cases
- LCD-14229 Move logic
- LCD-14229 ThemeJS type is not yet ready for use
- LCD-14229 manually remove CET type from metadata until SF fix is available
- LCD-14229 add sample templates for 6 client extension types
- LCD-14229 Baseline
- LCD-14229 use window.alert instead

### CODE REVIEW

**Comment by gamerson** [comment]
ci:forward

**Comment by gamerson** [comment]
ci:forward

**Comment by gamerson** [comment]
ci:reevaluate:1297401_3448

**Comment by gamerson** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Pull request closed without merging**
