### PR TITLE
Add NPM CACHE

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test

**Comment by lawrence-lee** [comment]
ci:reopen

**Comment by lawrence-lee** [comment]
ci:retest

**Comment by lawrence-lee** [comment]
ci:retest

**Comment by lawrence-lee** [comment]
ci:retest

**Comment by lawrence-lee** [comment]
ci:retest

**Comment by lawrence-lee** [comment]
ci:reopen

**Comment by lawrence-lee** [comment]
ci:retest

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/lawrence-lee/liferay-portal/pull/74. [See changes here.](https://github.com/gamerson/liferay-portal/compare/f8e827edd228~1...f8e827edd228) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
