### PR TITLE
LPS 187069 restore config

### PR DESCRIPTION
**Pull request by gamerson**
LPS-187069 Restore config

### CODE REVIEW

**Comment by gamerson** [comment]
ci:forward

**Comment by gamerson** [comment]
ci:forward:force

**Comment by gamerson** [comment]
ci:forward:force

**Comment by welitonpe** [comment]
ci:forward:force

**Comment by gamerson** [comment]
manually forwarded here: https://github.com/brianchandotcom/liferay-portal/pull/139742

**Pull request closed without merging**
