### PR TITLE
LPS 186072 Spring Boot Public Endpoint Configuration

### PR DESCRIPTION
**Pull request by allen-ziegenfus**
Here are the changes we discussed @gamerson  - let me know what you think

cc: @rotty3000 

@Alec-Shay Is this enough for you to get your spring boot sample working? With this PR you can add in a comma delimited list of public endpoints

### CODE REVIEW

**Comment by Alec-Shay** [comment]
Hey @allen-ziegenfus,

Unless I'm missing something, this looks like it would work good to enable our use case, yeah. Because we're in a rush to get our example merged ASAP, we will probably have to go with our workaround and go back and revise to use this later, but I think it would certainly look better when we do so.

**Comment by gamerson** [comment]
ci:help

**Comment by gamerson** [comment]
ci:test:liferay-sample-workspace

**Comment by gamerson** [comment]
ci:forward

**Comment by gamerson** [comment]
hey @allen-ziegenfus  can you check out the failing poshi tests on the sample-workspace suite?

**Comment by gamerson** [comment]
running tests here: https://github.com/gamerson/liferay-portal/pull/599

**Pull request closed without merging**
