### PR TITLE
Add 7.1 Project Template Tests

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:relevant

**Comment by lawrence-lee** [comment]
ci:reopen

**Comment by lawrence-lee** [comment]
ci:test:relevant

**Comment by lawrence-lee** [comment]
ci:test:relevant

**Comment by lawrence-lee** [comment]
@gamerson those failures arent because of project templates test

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-portal/pull/143. [See changes here.](https://github.com/gamerson/liferay-portal/compare/7244e4a0ccd4~1...7244e4a0ccd4) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/Ithildir/liferay-portal/pull/1038. [See changes here.](https://github.com/gamerson/liferay-portal/compare/61423aa747dc~11...61423aa747dc) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
