### PR TITLE
LPS-122967 configure processResources only if buildCSS exists

### PR DESCRIPTION
**Pull request by gamerson**
@lawrence-lee I made additional fix here.  If test passes you could cherry pick these two commits.

### CODE REVIEW

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
ci:test:gradle-plugins

**Comment by lawrence-lee** [comment]
Just started reviewing :)

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
ci:test:gradle-plugins

**Comment by lawrence-lee** [comment]
Just started reviewing :)

**Comment by lawrence-lee** [comment]
This has already been merged.

**Pull request closed without merging**
