### PR TITLE
LPS-79495 store and validate liferay version range

### PR DESCRIPTION
**Pull request by christopherbryanboyd**
Hi @gamerson , this addresses https://issues.liferay.com/browse/LPS-79495

### CODE REVIEW

**Comment by christopherbryanboyd** [comment]
ci:test

**Comment by christopherbryanboyd** [comment]
ci:reopen

**Comment by christopherbryanboyd** [comment]
ci:retest

**Comment by christopherbryanboyd** [comment]
ci:retest

**Comment by gamerson** [comment]
hey @christopherbryanboyd  is anything more needed here?  Has this already been addressed?

**Comment by christopherbryanboyd** [comment]
ci:test

**Comment by christopherbryanboyd** [comment]
Hey @gamerson , I think this is ready to go, the bndlib fix (requiring the pom.xml's dependency on bnd being bumped to 3.5.0) was refactored out and into a separate PR for Andrea here https://github.com/Ithildir/liferay-portal/pull/988, I have removed that change from this PR and rebased onto master.
This PR also required adding _source-formatter-suppressions.xml_ to the projects, I put these files in a separate commit so that we can remove them easily once SF is updated to support the new bnd instruction _Liferay-Versions_.

**Comment by christopherbryanboyd** [comment]
ci:retest

**Comment by christopherbryanboyd** [comment]
ci:stop

**Comment by christopherbryanboyd** [comment]
ci:retest

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-portal/pull/111. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
