### PR TITLE
LPS-79004: Use latest Project Template archetypes

### PR DESCRIPTION
**Pull request by christopherbryanboyd**
Hi @gamerson , this addresses https://issues.liferay.com/browse/LPS-79004

### CODE REVIEW

**Comment by christopherbryanboyd** [comment]
ci:test

**Comment by gamerson** [comment]
ci:stop

**Comment by gamerson** [comment]
ci:retest

**Comment by gamerson** [comment]
ci:test

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-portal/pull/90. [See changes here.](https://github.com/gamerson/liferay-portal/compare/e53d3f3~5...e53d3f3) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
