### PR TITLE
LPS-101463 setupTestableTomcat should depend on initBundle if bundles folder does not exist

### PR DESCRIPTION
**Pull request by christopherbryanboyd**
Hi @gamerson , this addresses https://issues.liferay.com/browse/LPS-101463

### CODE REVIEW

**Comment by christopherbryanboyd** [comment]
ci:test:relevant

**Comment by christopherbryanboyd** [comment]
ci:test:sf

**Comment by christopherbryanboyd** [comment]
ci:test:bundle

**Comment by christopherbryanboyd** [comment]
ci:test:sf

**Comment by christopherbryanboyd** [comment]
ci:test:relevant

**Comment by christopherbryanboyd** [comment]
ci:test:bundle

**Comment by gamerson** [comment]
ci:test:gradle-plugins

**Comment by gamerson** [comment]
hey @christopherbryanboyd  when testing workspace changes the only test that is really useful is ci_test_gradle-plugins . because nothing in the portal that is tested by ci_test_bundle or ci_test_relevant is using workspace .

**Comment by christopherbryanboyd** [comment]
> hey @christopherbryanboyd when testing workspace changes the only test that is really useful is ci_test_gradle-plugins . because nothing in the portal that is tested by ci_test_bundle or ci_test_relevant is using workspace .

Understood, will do in the future.

**Comment by gamerson** [comment]
Included in https://github.com/gamerson/liferay-portal/pull/370

**Pull request closed without merging**
