### PR TITLE
Fix Sample Custom Element 2

### PR DESCRIPTION
**Pull request by allen-ziegenfus**
@gamerson  By moving the oAuth code up outside of the render function it runs on module import and was causing the Hello World components not to render (in the case where the spring boot extension is not loaded). I added some error handling there so it is ok.

Alternatively we could check for the oAuth profile in `index.js` and pass it in if it exists.

Is it crucial to include all these examples together? I think it would be simpler to divide them up rather than having this if logic and rendering one thing or another .

### CODE REVIEW

**Comment by joshchong** [comment]
ci:test:liferay-sample-workspace

**Comment by joshchong** [comment]
ci:test:relevant

**Comment by joshchong** [comment]
@allen-ziegenfus @gamerson the CI tests confirms that this fixes the issue with sample 2. The rest of the CI test results look good as well.

**Comment by gamerson** [comment]
ci:forward

**Pull request closed without merging**
