### PR TITLE
LPS-104646 FAKE GRADLE CACHE

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:gradle-plugins

**Comment by lawrence-lee** [comment]
@petershin, Can you show me an example of the `git-commit-plugins` that I should be sending?

**Comment by petershin** [comment]
@lawrence-lee - That file only needs to be updated if you want to use a specific SHA for `liferay-plugins-ee`.

**Comment by petershin** [comment]
@lawrence-lee - I'll take a look at the `gradle-plugins-workspace` failures this afternoon

**Comment by lawrence-lee** [comment]
@petershin , got it. Thanks for looking into the failures. I'd still like Greg's review before this gets merged.

**Comment by petershin** [comment]
Testing a fix for the failures here: https://github.com/petershin/liferay-portal/pull/804

**Comment by lawrence-lee** [comment]
pushed here: https://github.com/gamerson/liferay-portal/pull/366

**Pull request closed without merging**
