### PR TITLE
Update Project Templates to 7.1

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:relevant

**Comment by lawrence-lee** [comment]
ci:reopen

**Comment by lawrence-lee** [comment]
ci:test:relevant

**Comment by lawrence-lee** [comment]
ci:test:relevant

**Comment by lawrence-lee** [comment]
ci:retest

**Comment by lawrence-lee** [comment]
ci:test:relevant

**Comment by lawrence-lee** [comment]
ci:reopen

**Comment by lawrence-lee** [comment]
@lawrence-lee, fix tests to make project template tests to be 7.1 default

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-portal/pull/164. [See changes here.](https://github.com/gamerson/liferay-portal/compare/69e1d1c984c8~1...69e1d1c984c8) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
