### PR TITLE
LPS 187069 cx metadata dxp poshi

### PR DESCRIPTION
**Pull request by gamerson**
try #3

### CODE REVIEW

**Comment by gamerson** [comment]
ci:test:liferay-sample-workspace

**Comment by gamerson** [comment]
ci:test:liferay-sample-worksace

**Comment by gamerson** [comment]
ci:test:liferay-sample-workspace

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
ci:test:liferay-sample-workspace

**Comment by gamerson** [comment]
ci:forward

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
ci:test:liferay-sample-workspace

**Comment by gamerson** [comment]
ci:test:liferay-sample-workspace

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
ci:forward

**Comment by gamerson** [comment]
ci:test:liferay-sample-workspace

**Comment by gamerson** [comment]
ci:forward

**Comment by gamerson** [comment]
ci:test:sf

**Comment by rotty3000** [comment]
ci:test:relevant

**Pull request closed without merging**
