### PR TITLE
lps-83755-with-updated-gradle-plugins

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:sf

**Comment by lawrence-lee** [comment]
ci:test:relevant

**Comment by lawrence-lee** [comment]
ci:stop

**Comment by lawrence-lee** [comment]
ci:test:sf

**Comment by lawrence-lee** [comment]
ci:test:relevant

**Comment by lawrence-lee** [comment]
ci:test:relevant

**Comment by lawrence-lee** [comment]
ci:test:relevant

**Comment by lawrence-lee** [comment]
ci:test:relevant

**Comment by lawrence-lee** [comment]
ci:test:relevant

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/petershin/liferay-portal/pull/176. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
