### PR TITLE
lps-102788

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:gradle-plugins

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
ci:test:gradle-plugins

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
```* What went wrong:
Execution failed for task ':runGradleTest'.
> assert logListener.log.contains("Dependency 'com.liferay:com.liferay.source.formatter:1.0.200', published")
         |           |   |
         |           |   false
         |           Please update your dependency to directly use the correct version 'xml-apis:xml-apis:1.0.b2'.
         |           Resolution will only pick dependencies of the relocated element.  Artifacts and other metadata will be ignored.
         |           Cached resource https://repository-cdn.liferay.com/nexus/content/groups/public/xml-apis/xml-apis/1.0.b2/xml-apis-1.0.b2.pom is up-to-date (lastModified: Fri Feb 09 00:30:46 UTC 2007).
         LogListener@71e67ff8``` 
doesnt look like has anything to do with my commits

**Comment by gamerson** [comment]
ci:test:gradle-plugins

**Comment by lawrence-lee** [comment]
ci:test:gradle-plugins

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
ci:stop

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
ci:stop

**Comment by lawrence-lee** [comment]
ci:test:gradle-plugins

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
@gamerson, I just fixed that last test error by adding the plugin dependency. I wonder if we should just push this up to Hugo lest gradle-plugins gets changed again.

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/hhuijser/liferay-portal/pull/3811. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
