### PR TITLE
LPS-88851 Handle fragment module in WatchTask

### PR DESCRIPTION
**Pull request by Seiphon**

### CODE REVIEW

**Comment by Seiphon** [comment]
ci:test

**Comment by Seiphon** [comment]
ci:retest

**Comment by Seiphon** [comment]
ci:test

**Comment by Seiphon** [comment]
Hi @gamerson , it seems the test failure is not caused by my fix.

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-portal/pull/250. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
