### PR TITLE
WCM-1486 Content Targeting template dependency updates for 7.1

### PR DESCRIPTION
**Pull request by codyhoag**
/cc @epgarcia

### CODE REVIEW

**Comment by gamerson** [comment]
hey @codyhoag  could you add a couple of new tests in `ProjectTemplateTests` for the new 7.1 content targeting?

**Comment by gamerson** [comment]
ci:test:project-templates

**Comment by codyhoag** [comment]
@gamerson I added 7.1 tests as you proposed. Hope it's correct; I haven't done much with test code 😅

**Comment by gamerson** [comment]
thanks @codyhoag

**Comment by gamerson** [comment]
ci:stop

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
ci:test:project-templates

**Comment by codyhoag** [comment]
ci:reopen

**Comment by codyhoag** [comment]
Fixed SF. I ran it before I sent... something weird must've happened

**Comment by codyhoag** [comment]
ci:test:sf

**Comment by codyhoag** [comment]
ci:test:sf

**Comment by codyhoag** [comment]
ci:test:project-templates

**Comment by codyhoag** [comment]
ci:test:project-templates

**Comment by gamerson** [comment]
good work @codyhoag  and @epgarcia

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/petershin/liferay-portal/pull/253. [See changes here.](https://github.com/gamerson/liferay-portal/compare/91422ab03b7a~1...91422ab03b7a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
