### PR TITLE
LPS-86838 Allowed create modules-ext project from maven archetype

### PR DESCRIPTION
**Pull request by Camork**

### CODE REVIEW

**Comment by gamerson** [comment]
hey @Camork  can you rebase this on master?  Also you only need the first two commits, and then you can send those two commits to me and I can make the changes needed to get them submitted to project templates.

**Comment by Camork** [comment]
Hey @gamerson , i removed your commits because we haven't pom.xml which will make test failed. and fix the test environment in windows.

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
ci:project-templates

**Comment by gamerson** [comment]
ci:test:project-templates

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-portal/pull/245. [See changes here.](https://github.com/gamerson/liferay-portal/compare/f0a4e0888c77~2...f0a4e0888c77) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
