### PR TITLE
LPS-81529 New test comparing service builder versions

### PR DESCRIPTION
**Pull request by christopherbryanboyd**
Update to https://github.com/gamerson/liferay-portal/pull/133

### CODE REVIEW

**Comment by christopherbryanboyd** [comment]
Hey @gamerson , I just rebased this on master to resolve conflicts.

**Comment by christopherbryanboyd** [comment]
ci:test

**Comment by christopherbryanboyd** [comment]
ci:stop

**Comment by christopherbryanboyd** [comment]
ci:test

**Comment by gamerson** [comment]
ci:stop

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-portal/pull/137. [See changes here.](https://github.com/gamerson/liferay-portal/compare/40694d12d433~1...40694d12d433) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
