### PR TITLE
LCD-14229 client extension templates and SF fix

### PR DESCRIPTION
**Pull request by gamerson**
cc @ling-alan-huang

### CODE REVIEW

**Comment by gamerson** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
SF failures are not related to this pull, I just sent the fix here https://github.com/ling-alan-huang/liferay-portal/pull/1159

**Comment by ling-alan-huang** [comment]
@gamerson we touched SF logic on this PR, so SF will check all files.

**Comment by gamerson** [comment]
ci:forward

**Comment by gamerson** [comment]
ci:forward

**Comment by gamerson** [comment]
ci:forward

**Comment by gamerson** [comment]
hey @ling-alan-huang  any idea how we can get SF test to pass here?  I've rebased on brian's latest master which should include your latest fix, but SF test still fails.

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
Rebase and resent: https://github.com/gamerson/liferay-portal/pull/553

**Pull request closed without merging**
