### PR TITLE
LPS-101814 upgrade the version of maven-jar-plugin to 3.1.2

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:stable

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
ci:stop

**Comment by lawrence-lee** [comment]
ci:stop

**Comment by lawrence-lee** [comment]
@jtydhr88 we need to create a fake gradle cache with the updated archetypes. I'll send a followup PR

**Comment by lawrence-lee** [comment]
new PR here: https://github.com/gamerson/liferay-portal/pull/347

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/lawrence-lee/liferay-portal/pull/130. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
