### PR TITLE
LPS-105959 FAKE GRADLE CACHE

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
@gamerson This pull has the following changes

1. Updated target platform to use 7.2 GA2 for 7.2 version
2. Use fully qualified GA versions instead of major.minor
3. Added exclusions for the 7.0 TP bugs
4. Added test cases for all versions of Liferay Portal in workspace. Previously only testing the latest GA

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/hhuijser/liferay-portal/pull/3920. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
