### PR TITLE
LPS-65475 Adds panel app

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
cc @juliocamarero

**Comment by juliocamarero** [comment]
👍

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/Ithildir/liferay-portal/pull/435. [See changes here.](https://github.com/gamerson/liferay-portal/compare/3fcbd5d~4...3fcbd5d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
