### PR TITLE
LPS-98417 FAKE GRADLE CACHE

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:sf

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
cc @natocesarrego @gabrielibson.

Once these tests pass, it should be merged. I think by early next week we can add this to blade.

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/hhuijser/liferay-portal/pull/4163. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
