### PR TITLE
LPS-59801 make _touch() can create files and folders both

### PR DESCRIPTION
**Pull request by AndyWu2015**

### CODE REVIEW

**Comment by AndyWu2015** [comment]
If the folder haven't been created , java can't check if it is a folder , so I just check if there is "." in the file name.

**Comment by gamerson** [comment]
Actually after thinking about this, we should have a new method, one for _touch() which is only for files and one for _mkdir() that will create the directory using the Files.createDirectories() command.

**Comment by AndyWu2015** [comment]
OK got it !

**Comment by AndyWu2015** [comment]
OK, got it !

**Pull request closed without merging**
