### PR TITLE
LRDOCS-3852 Gradle Properties descriptions

### PR DESCRIPTION
**Pull request by codyhoag**
Hey Greg,

This PR provides descriptions for the Gradle properties in a Workspace. Can you review?

I also updated the Microsoft Translator property and provided a description for that (copied from `build.properties`). It would probably be best if @Ithildir reviewed that, for accuracy.

Let me know if there are any inaccuracies with the descriptions and I'll update accordingly.

Thanks!

### CODE REVIEW

**Comment by Ithildir** [comment]
Hi @codyhoag,
I wrote the original comment in `build.properties`, so, if you simply copied it, than it's already okay for me 😊

**Comment by codyhoag** [comment]
@Ithildir sounds good! It was a strict copy/paste. As we discussed earlier, I removed the two outdated Microsoft translator properties too. The new one you added (`microsoft.translator.subscription.key`) is now the only one provided in the `gradle.properties`.

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/Ithildir/liferay-portal/pull/749. [See changes here.](https://github.com/gamerson/liferay-portal/compare/a80a2a2~1...a80a2a2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/codyhoag/liferay-portal/pull/87. [See changes here.](https://github.com/gamerson/liferay-portal/compare/a80a2a2~1...a80a2a2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
