### PR TITLE
LPS-152789 Add spring context when using the portal api jar

### PR DESCRIPTION
**Pull request by Seiphon**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:gradle-plugins

**Comment by lawrence-lee** [comment]
Thanks for reviewing this @gamerson

**Review by gamerson — APPROVED** [review]
LGTM!

**Comment by gamerson** [comment]
If the gradle plugins tests pass, i'll send it on to Peter.

**Comment by lawrence-lee** [comment]
These are the failing gradle tests. @gamerson , i dont see the springContext test in here. I believe @Seiphon has fixes for the remaining test failures in another PR. Is that correct?

```
     [exec] gradleTest.compatibilityTests.dsl.groovy.ProvidedModulesSpec > ProvidedModules : Gradle 5.6.4 using dsl.groovy FAILED
     [exec]     org.gradle.testkit.runner.UnexpectedBuildFailure at ProvidedModules.dsl.groovySpec.groovy:185
     [exec] 
     [exec] gradleTest.compatibilityTests.dsl.groovy.ProvidedModulesSpec > ProvidedModules : Gradle 6.6.1 using dsl.groovy FAILED
     [exec]     org.gradle.testkit.runner.UnexpectedBuildFailure at ProvidedModules.dsl.groovySpec.groovy:185
     [exec] 
     [exec] gradleTest.compatibilityTests.dsl.groovy.StartDockerContainerSpec > StartDockerContainer : Gradle 5.6.4 using dsl.groovy FAILED
     [exec]     org.gradle.testkit.runner.UnexpectedBuildFailure at StartDockerContainer.dsl.groovySpec.groovy:185
     [exec] 
     [exec] gradleTest.compatibilityTests.dsl.groovy.StartDockerContainerSpec > StartDockerContainer : Gradle 6.6.1 using dsl.groovy FAILED
     [exec]     org.gradle.testkit.runner.UnexpectedBuildFailure at StartDockerContainer.dsl.groovySpec.groovy:185
     [exec] 
     [exec] gradleTest.compatibilityTests.dsl.groovy.TestIntegrationClassesSpec > TestIntegrationClasses : Gradle 5.6.4 using dsl.groovy FAILED
     [exec]     org.gradle.testkit.runner.UnexpectedBuildFailure at TestIntegrationClasses.dsl.groovySpec.groovy:185
     [exec] 
     [exec] gradleTest.compatibilityTests.dsl.groovy.TestIntegrationClassesSpec > TestIntegrationClasses : Gradle 6.6.1 using dsl.groovy FAILED
     [exec]     org.gradle.testkit.runner.UnexpectedBuildFailure at TestIntegrationClasses.dsl.groovySpec.groovy:185
     [exec] 
     [exec] gradleTest.compatibilityTests.dsl.groovy.StartDockerContainerWithScriptSpec > StartDockerContainerWithScript : Gradle 5.6.4 using dsl.groovy FAILED
     [exec]     org.gradle.testkit.runner.UnexpectedBuildFailure at StartDockerContainerWithScript.dsl.groovySpec.groovy:185
     [exec] 
     [exec] gradleTest.compatibilityTests.dsl.groovy.StartDockerContainerWithScriptSpec > StartDockerContainerWithScript : Gradle 6.6.1 using dsl.groovy FAILED
     [exec]     org.gradle.testkit.runner.UnexpectedBuildFailure at StartDockerContainerWithScript.dsl.groovySpec.groovy:185
     [exec] 
     [exec] gradleTest.compatibilityTests.dsl.groovy.StartDockerContainerWithScriptsSpec > StartDockerContainerWithScripts : Gradle 5.6.4 using dsl.groovy FAILED
     [exec]     org.gradle.testkit.runner.UnexpectedBuildFailure at StartDockerContainerWithScripts.dsl.groovySpec.groovy:185
     [exec] 
     [exec] gradleTest.compatibilityTests.dsl.groovy.StartDockerContainerWithScriptsSpec > StartDockerContainerWithScripts : Gradle 6.6.1 using dsl.groovy FAILED
     [exec]     org.gradle.testkit.runner.UnexpectedBuildFailure at StartDockerContainerWithScripts.dsl.groovySpec.groovy:185
     [exec] 
     [exec] gradleTest.compatibilityTests.dsl.groovy.ProductInfoBadKeySpec > ProductInfoBadKey : Gradle 5.6.4 using dsl.groovy FAILED
     [exec]     org.gradle.testkit.runner.UnexpectedBuildFailure at ProductInfoBadKey.dsl.groovySpec.groovy:185
     [exec] 
     [exec] gradleTest.compatibilityTests.dsl.groovy.ProductInfoBadKeySpec > ProductInfoBadKey : Gradle 6.6.1 using dsl.groovy FAILED
     [exec]     org.gradle.testkit.runner.UnexpectedBuildFailure at ProductInfoBadKey.dsl.groovySpec.groovy:185
     [exec] 
     [exec] 124 tests completed, 12 failed
     [exec] 
     [exec] > Task :sdk:gradle-plugins-workspace:gradleTest FAILED
```

**Comment by gamerson** [comment]
Ok, then I'll go ahead and send to Peter and let him know the same.

**Comment by gamerson** [comment]
resent here: https://github.com/petershin/liferay-portal/pull/1650

**Pull request closed without merging**
