### PR TITLE
War Hook Project Template

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by gamerson** [comment]
@lawrence-lee more source formatting is needed :)

**Comment by gamerson** [comment]
ci:retest

**Comment by gamerson** [comment]
hey @lawrence-lee  see failures here: https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=3,label_exp=!master/150442//testReport/com.liferay.project.templates/ProjectTemplatesTest/testBuildTemplateWarHook

**Comment by lawrence-lee** [comment]
ci:retest

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/Ithildir/liferay-portal/pull/783. [See changes here.](https://github.com/gamerson/liferay-portal/compare/9f8de44f~1...9f8de44f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
