### PR TITLE
Test NPM Cache in gradle

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:relevant

**Comment by lawrence-lee** [comment]
ci:test:relevant

**Comment by lawrence-lee** [comment]
@gamerson as far as i can tell, the gradle part seems to be working. the tests pass ci. I was able to break it by passing in "http://foobar.com" as the registry url. What do we need to update for maven?

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/Ithildir/liferay-portal/pull/1015. [See changes here.](https://github.com/gamerson/liferay-portal/compare/a5ec06348445~2...a5ec06348445) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/Ithildir/liferay-portal/pull/1016. [See changes here.](https://github.com/gamerson/liferay-portal/compare/8b6d852ac361~2...8b6d852ac361) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
