### PR TITLE
LPS-65471 Improve the template to show the asset title

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
cc @juliocamarero

**Comment by juliocamarero** [comment]
👍

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
@ealonso @juliocamarero how would I go about testing this?

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/Ithildir/liferay-portal/pull/436. [See changes here.](https://github.com/gamerson/liferay-portal/compare/e1326ee~6...e1326ee) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Hey @gamerson,

To test it you should go to add panel and create a new asset, for example a "blog entry".

welcome_-_liferay

So, when you add the "blog entry" a portlet is added to the page, this portlet should be your portlet. Also, if you have already created a "blog entry" you can drag and drop the blog entry into the page and your portlet should be added.

You can use any asset except web content, because we have a custom add portlet provider for this.

Regards,
Eudaldo

**Comment by gamerson** [comment]
So lets say I have a new provider, how does it get "linked" to blogs entry?

On Mon, Jul 4, 2016 at 2:36 AM, Eudaldo Alonso <notifications@github.com>
wrote:

> Hey @gamerson <https://github.com/gamerson>,
>
> To test it you should go to add panel and create a new asset, for example
> a "blog entry".
>
> [image: welcome_-_liferay]
> <https://cloud.githubusercontent.com/assets/922631/16553607/df116b88-41c9-11e6-88ca-f8c6de5ba672.png>
>
> So, when you add the "blog entry" a portlet is added to the page, this
> portlet should be your portlet. Also, if you have already created a "blog
> entry" you can drag and drop the blog entry into the page and your portlet
> should be added.
>
> You can use any asset except web content, because we have a custom add
> portlet provider for this.
>
> Regards,
> Eudaldo
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/gamerson/liferay-portal/pull/57#issuecomment-230224784>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAkVFehsWAtiVTNXTYjh1lEUKqB_j3Spks5qSLgEgaJpZM4ItYkO>
> .
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Pull request closed without merging**
