### PR TITLE
LPS-109787 Fix gradle tests

### PR DESCRIPTION
**Pull request by allen-ziegenfus**

### CODE REVIEW

**Comment by allen-ziegenfus** [comment]
hi @gamerson 

i found one typo and some invalid assertions, it's working for me now

image

**Comment by gamerson** [comment]
Thanks so much Allen!

**Comment by gamerson** [comment]
I'm gonna run the tests here before sending it on.

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
ci:test:gradle-plugins

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/petershin/liferay-portal/pull/907. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
@allen-ziegenfus  all test passed! Thanks!

**Comment by allen-ziegenfus** [comment]
great!! so glad i could help out @gamerson

**Pull request closed without merging**
