### PR TITLE
LPS-75556 Use NPMResolver from blade’s npm project templates

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:reopen

**Comment by izaera** [comment]
ci:retest

**Comment by gamerson** [comment]
hey @izaera  Lets wait until https://github.com/brianchandotcom/liferay-portal/pull/52696 is merged, and then we can rebase this on top of that.

**Comment by izaera** [comment]
😱  Conflicts! Conflicts everywhere

I'm doing the rebase. Will resend.

**Pull request closed without merging**
