### PR TITLE
LPS-71728

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:stop

**Comment by gamerson** [comment]
ci:retest

**Comment by gamerson** [comment]
hey @Ithildir this change should have no affect on current bundles as none of them are using the new instruction -`liferay-aggregate-resource-bundles` so this change should produce the same output as before.

**Comment by gamerson** [comment]
nevermind I found a problem:
```
* What went wrong:
Execution failed for task ':bundlesDiffTest'.
> [directory 'maven' - blade.language.web-1.0.0.jar
  CHANGED    MANIFEST   <manifest>
   REMOVED    HEADER     Provide-Capability:liferay.resource.bundle;resource.bundle.base.name:String="content.Language";bundle.symbolic.name="blade.language.web",liferay.resource.bundle;resource.bundle.aggregate:String="(&(bundle.symbolic.name=blade.language.web)(!(aggregate=true))),(bundle.symbolic.name=blade.language)";bundle.symbolic.name="blade.language.web";resource.bundle.base.name="content.Language";service.ranking:long=1;aggregate=true;servlet.context.name=blade-language-web,osgi.service;objectClass:List<String>="javax.portlet.Portlet"
   ADDED      HEADER     Provide-Capability:osgi.service;objectClass:List<String>="javax.portlet.Portlet",liferay.resource.bundle;bundle.symbolic.name="blade.language.web";resource.bundle.base.name="content.Language"
   REMOVED    HEADER     Require-Capability:liferay.resource.bundle;filter:="(bundle.symbolic.name=blade.language)",osgi.extender;filter:="(&(osgi.extender=jsp.taglib)(uri=http://java.sun.com/portlet_2_0))",osgi.extender;filter:="(&(osgi.extender=jsp.taglib)(uri=http://liferay.com/tld/aui))",osgi.extender;filter:="(&(osgi.extender=jsp.taglib)(uri=http://liferay.com/tld/portlet))",osgi.extender;filter:="(&(osgi.extender=jsp.taglib)(uri=http://liferay.com/tld/theme))",osgi.extender;filter:="(&(osgi.extender=jsp.taglib)(uri=http://liferay.com/tld/ui))",osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"
   ADDED      HEADER     Require-Capability:osgi.extender;filter:="(&(osgi.extender=jsp.taglib)(uri=http://java.sun.com/portlet_2_0))",osgi.extender;filter:="(&(osgi.extender=jsp.taglib)(uri=http://liferay.com/tld/aui))",osgi.extender;filter:="(&(osgi.extender=jsp.taglib)(uri=http://liferay.com/tld/portlet))",osgi.extender;filter:="(&(osgi.extender=jsp.taglib)(uri=http://liferay.com/tld/theme))",osgi.extender;filter:="(&(osgi.extender=jsp.taglib)(uri=http://liferay.com/tld/ui))",osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"
  ]
```

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/Ithildir/liferay-portal/pull/682. [See changes here.](https://github.com/gamerson/liferay-portal/compare/a505ab5~1...a505ab5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
