### PR TITLE
LCD-14229 client extension templates and SF fix

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@gamerson can you help fix SF issues on the front-end code?

**Comment by gamerson** [comment]
hey @ling-alan-huang  yeah I'll update that global.js to something that passes prettier check

**Comment by gamerson** [comment]
Resent here: #554

**Pull request closed without merging**
