### PR TITLE
SoyPortlet Archetype is missing a Provide-Capability header

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/Ithildir/liferay-portal/pull/821. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
hey @brunobasto  I sent your pull onto Andrea but I removed the commit for the title change.  The current title matches our other templates and I want ot keep everything the same.  We could propose to make all the titles more friendly which I'm fine discussing, but I would want to change them all, not just the Soy portlet.

**Comment by gamerson** [comment]
ci:stop

**Comment by brunobasto** [comment]
Thanks, @gamerson! Yeah, I agree.

**Pull request closed without merging**
