### PR TITLE
LPS-59801 let servicebuilder create sql folder if there is no before

### PR DESCRIPTION
**Pull request by AndyWu2015**

### CODE REVIEW

**Comment by gamerson** [comment]
Submitted: https://github.com/brianchandotcom/liferay-portal/pull/31541

Thanks

**Comment by AndyWu2015** [comment]
Hi Greg , I tested the latest servicebuilder but it still can't create sql folder , I saw your code just added creating dir function to _touch(File file) method but if there is no sql folder , it (line : 3187,3389,3472) will return immediately and will not execute _touch method . Can you check that ? Or I will resend a pull request . thanks.

**Comment by gamerson** [comment]
Yes can you resend based after my change?  Yes in _createSQLIndexes()  if
sqlDir doesn't exist we should call _touch(sqlDir)

On Wed, Oct 28, 2015 at 9:09 PM, Andy Wu <notifications@github.com> wrote:

> Hi Greg , I tested the latest servicebuilder but it still can't create sql
> folder , I saw your code just added creating dir function to _touch(File
> file) method but if there is no sql folder , it (line : 3187,3389,3472)
> will return immediately and will not execute _touch method . Can you check
> that ? Or I will resend a pull request . thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gamerson/liferay-portal/pull/15#issuecomment-152051989>
> .
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by AndyWu2015** [comment]
Done

**Pull request closed without merging**
