### PR TITLE
LPS-81648 Fix project-templates-rest

### PR DESCRIPTION
**Pull request by csierra**
hey @gamerson, 
@ithildir and I have found a problem with this template. 

It would also be great if we could upgrade this template to use the JAX-RS Whiteboard in 7.1, which would  be the preferred and cleaner approach.

### CODE REVIEW

**Comment by csierra** [comment]
ci:test

**Comment by gamerson** [comment]
hey @csierra  can you point to an example JaxRS using whiteboard and we can add a ticket to work on converting it for 7.1

**Comment by csierra** [comment]
hey, sure: 
https://github.com/liferay/liferay-portal/blob/master/modules/apps/oauth2-provider/oauth2-provider-rest/src/main/java/com/liferay/oauth2/provider/rest/internal/endpoint/OAuth2EndpointApplication.java
https://github.com/liferay/liferay-portal/blob/master/modules/apps/apio-architect/apio-architect-application/src/main/java/com/liferay/apio/architect/application/internal/ApioApplication.java

it needs to register a `javax.ws.rs.core.Application` with a property with the path: `osgi.jaxrs.application.base`

we don't need to use the configurations anymore

**Comment by gamerson** [comment]
ci:reopen

**Comment by gamerson** [comment]
Hey @csierra  This all looks good!  Sent here: https://github.com/Ithildir/liferay-portal/pull/1022

**Pull request closed without merging**
