### PR TITLE
Project Template Workspace Tests

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:retest

**Comment by gamerson** [comment]
ci:retest

**Comment by lawrence-lee** [comment]
ci:retest

**Comment by lawrence-lee** [comment]
ci:retest

**Comment by lawrence-lee** [comment]
@gamerson I fixed the SF error and force pushed the change

**Comment by gamerson** [comment]
ci:retest

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/Ithildir/liferay-portal/pull/721. [See changes here.](https://github.com/gamerson/liferay-portal/compare/3b882a2~4...3b882a2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
ci:stop

**Pull request closed without merging**
