### PR TITLE
LPS-107155 add dependencyManagement task to get all target platform dependencies

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
ci:test:gradle-plugins

**Comment by simonjhy** [comment]
ci:test:gradle-plugins

**Comment by simonjhy** [comment]
ci:test:sf

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-portal/pull/386. [See changes here.](https://github.com/gamerson/liferay-portal/compare/68853db2a912~11...68853db2a912) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
