### PR TITLE
LPS-117861 Add Liferay Nexus as archetype catalog

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:sf

**Comment by lawrence-lee** [comment]
ci:test:relevant

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-portal/pull/461. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
