### PR TITLE
BLADE-604 FAKE GRADLE CACHE

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:sf

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by gamerson** [comment]
ci:stop

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-portal/pull/468. [See changes here.](https://github.com/gamerson/liferay-portal/compare/34427b307a9a~1...34427b307a9a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
