### PR TITLE
LPS-83755

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:relevant

**Comment by lawrence-lee** [comment]
ci:test:relevant

**Comment by lawrence-lee** [comment]
@gamerson I think this is ready to move along. I'll add the tests in another pull once the artifacts are published.

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
hey @lawrence-lee  i'll close this and you can resend it once you have the pom.xml changes in the archetype resources.

**Pull request closed without merging**
