### PR TITLE
LPS-99895 sf

### PR DESCRIPTION
**Pull request by christopherbryanboyd**

### CODE REVIEW

**Comment by christopherbryanboyd** [comment]
ci:test:sf

**Comment by christopherbryanboyd** [comment]
ci:test:gradle-plugins

**Comment by christopherbryanboyd** [comment]
ci:test:relevant

**Comment by christopherbryanboyd** [comment]
ci:test:bundle

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/petershin/liferay-portal/pull/644. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
