### PR TITLE
LPS-181325 SF

### PR DESCRIPTION
**Pull request by kevenleone**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:forward

**Comment by gamerson** [comment]
hey @kevenleone  thanks for the review!  The only question I have is this one:
https://github.com/gamerson/liferay-portal/pull/594/commits/d68aae062e7d6ee8d2299c1ee4b301694ba71c29#diff-93e16c54502de0411d1b57f433e3d872825b43c111f80dda81ee2123a679c4b1

You can see the file that I'm trying to match from the spring-boot sample is this file:
https://github.com/liferay/liferay-portal/blob/master/workspaces/liferay-sample-workspace/client-extensions/liferay-sample-etc-spring-boot/src/main/resources/application-default.properties

But the current file is not sorted, which you fixed.  So we can see bchan's preference.  Thanks again!

**Comment by kevenleone** [comment]
Got it @gamerson, in fact SF orders to sort the object, if really necessary we can disable that rule, but it's not ideal since we are trying to follow the Source Format from portal.

Maybe, using `.env` we can have an expected similars to https://github.com/liferay/liferay-portal/blob/master/workspaces/liferay-sample-workspace/client-extensions/liferay-sample-etc-spring-boot/src/main/resources/application-default.properties

and create the groups for properties, that way is not necessary to be ordered, example:

```
#
# LXC
#

com.liferay.lxc.dxp.domains=localhost:8080
com.liferay.lxc.dxp.mainDomain=localhost:8080
com.liferay.lxc.dxp.server.protocol=http

#
# OAuth
#

liferay.oauth.application.external.reference.codes=liferay-sample-etc-spring-boot-oauth-application-user-agent

#
# Spring Boot
#

server.port=58081
```

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by gamerson** [comment]
thanks @kevenleone  i'm sending it on to bchan.

**Comment by gamerson** [comment]
ci:forward

**Comment by gamerson** [comment]
resent here: https://github.com/gamerson/liferay-portal/pull/595

**Pull request closed without merging**
