### PR TITLE
LRQA-42647 | master

### PR DESCRIPTION
**Pull request by jpince**
https://issues.liferay.com/browse/LRQA-42647

### CODE REVIEW

**Comment by jpince** [comment]
@gamerson this won't actually fix the POSHI tests that are failing (see [LRQA-42647](https://issues.liferay.com/browse/LRQA-42647)), but I figured it'd be worthwhile to get the necessary changes in for whenever the latest templates are published to maven.

Changes in build.gradle is to match what's in the liferay-blade-samples repo https://github.com/liferay/liferay-blade-samples/commit/785ce9ef5e3e52dfa74eb723bb4d54432e62e9c1#r30026549. Not the typo I asked Cody to fix, we may also need a new version published for that template to work properly?

Not sure if the changes in pom.xml are needed... I did them because they made sense to me, but I'm really not sure what the impact of this is.

The latest version 1.0.8 is on nexus but not on maven, Chas is looking into this, see https://issues.sonatype.org/browse/NEXUS-17770. I don't think this will have a net negative impact, the POSHI tests are already failing anyways.

cc/ @izaera @alee8888 @lawrence-lee

**Comment by lawrence-lee** [comment]
ci:test

**Comment by gamerson** [comment]
ci:reopen

**Comment by gamerson** [comment]
thanks @jpince  I'll take a look asap.

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/petershin/liferay-portal/pull/183. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
thanks @jpince

**Pull request closed without merging**
