### PR TITLE
lps-89515

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:sf

**Comment by lawrence-lee** [comment]
ci:test:relevant

**Comment by lawrence-lee** [comment]
ci:test:sf

**Comment by lawrence-lee** [comment]
ci:test:relevant

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/petershin/liferay-portal/pull/368. [See changes here.](https://github.com/gamerson/liferay-portal/compare/edb71a7b65c8~2...edb71a7b65c8) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
