### PR TITLE
LPS-86544 Fix the issue of wrong dtd version when choose a version of liferay

### PR DESCRIPTION
**Pull request by Seiphon**
Hi @gamerson

Last time, the test failed, I guess the reason is that the templates versions were not changed. Because when I test on my end, it works well if I upgrade the versions. But I am not sure should I upgrade the version manually. I added a commit to do upgrade versions, if I needn't do this, please let me know, I will resend the pull request.

Br,
Seiphon
cc @jtydhr88

### CODE REVIEW

**Comment by Seiphon** [comment]
ci:test:sf

**Comment by Seiphon** [comment]
ci:test:project-templates

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/Seiphon/liferay-portal/pull/5. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Hey @Seiphon  I've made some comments for some required changes here: https://github.com/Seiphon/liferay-portal/pull/5

**Pull request closed without merging**
