### PR TITLE
lps-95688

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:sf

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by lawrence-lee** [comment]
ci:stop

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/petershin/liferay-portal/pull/524. [See changes here.](https://github.com/gamerson/liferay-portal/compare/2f651fad98e3~4...2f651fad98e3) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
