### PR TITLE
LPS-79496 Check liferayVersion with "startsWith"

### PR DESCRIPTION
**Pull request by christopherbryanboyd**
Hi @gamerson , this addresses https://issues.liferay.com/browse/LPS-79496

### CODE REVIEW

**Comment by christopherbryanboyd** [comment]
ci:test

**Comment by gamerson** [comment]
ci:stop

**Comment by gamerson** [comment]
ci:stop

**Comment by gamerson** [comment]
ci:test:relevant

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-portal/pull/107. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
