### PR TITLE
LPS-65336 Creates new template for control menu entry

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
cc:\ @juliocamarero

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/39225. [See changes here.](https://github.com/gamerson/liferay-portal/compare/6e77def~7...6e77def) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/Ithildir/liferay-portal/pull/352. [See changes here.](https://github.com/gamerson/liferay-portal/compare/d8bd978~10...d8bd978) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
