### PR TITLE
LPS-99895

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:gradle-plugins

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by petershin** [comment]
@lawrence-lee - The `ci:test:gradle-plugins` suite passed here: https://github.com/petershin/liferay-portal/pull/663#issuecomment-524438757

I had to add one more commit.  The easiest way to get that change is to remove all my commits and than to rebase w master after my pull is merged into upstream

**Comment by lawrence-lee** [comment]
@petershin, Thanks. will do.

**Comment by lawrence-lee** [comment]
ci:stop

**Comment by lawrence-lee** [comment]
ci:stop

**Pull request closed without merging**
