### PR TITLE
LPS-83436 Allow single hash lines for Language.properties for velocity

### PR DESCRIPTION
**Pull request by natocesarrego**

### CODE REVIEW

**Comment by natocesarrego** [comment]
ci:test

**Comment by gamerson** [comment]
ci:test:relevant

**Comment by gamerson** [comment]
ci:stop

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/Ithildir/liferay-portal/pull/1066. [See changes here.](https://github.com/gamerson/liferay-portal/compare/7342a2f4871c~5...7342a2f4871c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Good job @natocesarrego !

**Comment by gamerson** [comment]
Sent to Andrea for review who is on PTO.

**Pull request closed without merging**
