### PR TITLE
LPS-118868 FAKE GRADLE CACHE

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
ci:test:gradle-plugins

**Comment by lawrence-lee** [comment]
Failing test should be fixed by this PR https://github.com/gamerson/liferay-portal/pull/463#issuecomment-673724435

**Comment by lawrence-lee** [comment]
@gamerson, Review please?

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/petershin/liferay-portal/pull/1154. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
