### PR TITLE
LPS-86370 unneeded

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:test:sf

**Comment by gamerson** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
ci:stop

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/lawrence-lee/liferay-portal/pull/94. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
