### PR TITLE
LPS-87102 Exploded bundles are run twice

### PR DESCRIPTION
**Pull request by tinatian**
Hi Greg,

Could you please take a look at my fix for this issue? I am not sure if this is going to cause regression.

cc @shuyangzhou

Thanks.
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
cc  @dantewang This is why we have test failure with servlet context class loader pool.

**Comment by tinatian** [comment]
@gamerson 
Could you please kindly prioritize this pull? It is a blocker of our fix (https://github.com/shuyangzhou/liferay-portal/pull/7016) for https://issues.liferay.com/browse/LPS-84130.

FYI @dantewang @daviddotzhang

Thanks.
Tina.

**Comment by gamerson** [comment]
hey @tinatian   I'm looking at it now.  Sorry was at devcon last week and just now seeing this.

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/shuyangzhou/liferay-portal/pull/7030. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
hey @tinatian  this looks safe to me!  I'll send it on to Shuyang, if I find regressions after further testing I'll send a followup.  The exploded war development feature using 'watch' has not been published yet, so its still an unlisted feature.

**Comment by tinatian** [comment]
Sounds great! Thanks @gamerson!

**Pull request closed without merging**
