### PR TITLE
blade-466

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:sf

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/hhuijser/liferay-portal/pull/3713. [See changes here.](https://github.com/gamerson/liferay-portal/compare/d29aca699bd0~1...d29aca699bd0) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
