### PR TITLE
LPS-65477 Blade templates for: Simulation Panel, Context Contributor, Portlet Toolbar Contributor and Portlet Configuration Icon

### PR DESCRIPTION
**Pull request by juliocamarero**
Blade ci pull here: https://github.com/gamerson/liferay-blade-cli/pull/116

### CODE REVIEW

**Comment by juliocamarero** [comment]
Hey @codyhoag we probably want to mention in the existing tutorials that we have blade templates for these extensions... what do you think?

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/42144. [See changes here.](https://github.com/gamerson/liferay-portal/compare/a3a8c16~5...a3a8c16) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/Ithildir/liferay-portal/pull/459. [See changes here.](https://github.com/gamerson/liferay-portal/compare/a3a8c16~5...a3a8c16) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
