### PR TITLE
LPS-114882 Add gradleTest for providedModules configuration in Target Platform

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:sf

**Comment by lawrence-lee** [comment]
ci:test:gradle-plugins

**Comment by lawrence-lee** [comment]
ci:test:gradle-plugins

**Comment by lawrence-lee** [comment]
All of the failures look unrelated to this PR. I'm not sure what's going on here. 

```
> Failed to notify project evaluation listener.
   > com.liferay.gradle.plugins.internal.util.GradleUtil.fetchTaskProvider(Lorg/gradle/api/Project;Ljava/lang/String;Ljava/lang/Class;)Lorg/gradle/api/tasks/TaskProvider;
```

**Comment by gamerson** [comment]
> All of the failures look unrelated to this PR. I'm not sure what's going on here.
> 
> ```
> > Failed to notify project evaluation listener.
>    > com.liferay.gradle.plugins.internal.util.GradleUtil.fetchTaskProvider(Lorg/gradle/api/Project;Ljava/lang/String;Ljava/lang/Class;)Lorg/gradle/api/tasks/TaskProvider;
> ```

It looks related to the task provider changes that Peter was talking about last week.  I'll send them on to peter.

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/petershin/liferay-portal/pull/1034. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
