### PR TITLE
LPS-111461 FAKE GRADLE CACHE

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:sf

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by gamerson** [comment]
ci:test:gradle-plugins

**Comment by gamerson** [comment]
ci:test:gradle-plugins

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-portal/pull/446. [See changes here.](https://github.com/gamerson/liferay-portal/compare/34a40b130f8d~1...34a40b130f8d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
