### PR TITLE
Inject mavenlocal into Project Template Tests

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:relevant

**Comment by lawrence-lee** [comment]
ci:test:relevant

**Comment by lawrence-lee** [comment]
ci:test:relevant

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/Ithildir/liferay-portal/pull/1021. [See changes here.](https://github.com/gamerson/liferay-portal/compare/b5565bb35261~1...b5565bb35261) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
