### PR TITLE
LPS-79272 remove mavenLocal()

### PR DESCRIPTION
**Pull request by christopherbryanboyd**
Hey @gamerson , this addresses https://issues.liferay.com/browse/LPS-79272

### CODE REVIEW

**Comment by christopherbryanboyd** [comment]
ci:test

**Comment by gamerson** [comment]
ci:retest

**Comment by gamerson** [comment]
hey @christopherbryanboyd  this looks good!

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/Ithildir/liferay-portal/pull/957. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
