### PR TITLE
LPS-105502 FAKE GRADLE CACHE

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:sf

**Comment by lawrence-lee** [comment]
ci:test:gradle-plugins

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/petershin/liferay-portal/pull/835. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
