### PR TITLE
Use latest project template tokens

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test

**Comment by lawrence-lee** [comment]
@gamerson I think this is ready. None of these look relevant to Project Templates

**Comment by gamerson** [comment]
thanks @lawrence-lee 

Can you update project templates to include new versions of the project templates that will be affected?

**Comment by lawrence-lee** [comment]
ci:test

**Comment by lawrence-lee** [comment]
@gamerson Done! I've also updated Project Templates to 4.0.0.

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/Ithildir/liferay-portal/pull/881. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
